### ISSUE TITLE
app.arm.src points to arm64 release

### ISSUE THREAD

**Issue by Fxsch** [YunoHost-Apps/prowlarr_ynh#11]
### Describe the bug

Opening Prowlarr in the browser results in a "502 Bad Gateway" error

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.3.6.3
- I have access to my server: Through SSH and the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

Normally install the application through the web interface

### Logs

https://paste.yunohost.org/raw/oqazohucek

This is the installation log

**Comment by Fxsch** [comment]
The issue seems to be that the daemon is not starting. When I run `journalctl -u prowlarr` in the terminal, it repeats this a few times until it says that the daemon couldn't be started at the end:

```
systemd[555]: prowlarr.service: Failed to execute command: Exec format error
systemd[555]: prowlarr.service: Failed at step EXEC spawning /opt/yunohost/prowlarr/Prowlarr: Exec format error
systemd[1]: prowlarr.service: Main process exited, code=exited, status=203/EXEC
systemd[1]: prowlarr.service: Failed with result 'exit-code'.
systemd[1]: prowlarr.service: Service RestartSec=100ms expired, scheduling restart.
systemd[1]: prowlarr.service: Scheduled restart job, restart counter is at 1.
systemd[1]: Stopped Prowlarr Daemon.
systemd[1]: Started Prowlarr Daemon.
```

**Comment by Fxsch** [comment]
I fixed it. It seems like this YunoHost package installed a version of Prowlarr for the wrong architecture. I replaced the files in `/opt/yunohost/prowlarr` with the files for arm that I downloaded off the Prowlarr GitHub repo and it worked.

**Comment by tituspijean** [comment]
Thank you for your report and investigation!
Indeed there's something wrong with the file pointing to the arm release, it points to the arm64 one.

**Comment by tituspijean** [comment]
@Fxsch @DJPlaya, this should be fixed now. Thanks for your reports!
