### ISSUE TITLE
Move configuration data outside of application folder

### ISSUE THREAD

**Issue by CwTiruve** [YunoHost-Apps/prowlarr_ynh#3]
Hi,

When I want to update Prowlarr, it's not working, there is the log :

Your Prowlarr configuration '/opt/yunohost/prowlarr/.data' is being stored in application folder '/opt/yunohost/prowlarr' which will cause data lost during the upgrade.

Do you know how can I upgrade prowlarr ?

**Comment by tituspijean** [comment]
Duplicate of #2.
